[ [ 0, 'Weyerhaeuser Company v. U.S. Fish and Wildlife Service' ],
  [ 1, 'Mount Lemmon Fire District v. Guido' ],
  [ 2, 'Gundy v. U.S.' ],
  [ 3, 'Madison v. Alabama' ],
  [ 4, 'New Prime Inc. v. Oliveira' ],
  [ 5, 'U.S. v. Stitt' ],
  [ 6, 'U.S. v. Sims' ],
  [ 7, 'Stokeling v. U.S.' ],
  [ 8, 'Nielsen v. Preap' ],
  [ 9, 'Air and Liquid Systems Corp. v. DeVries' ],
  [ 10, 'Lamps Plus Inc. v. Varela' ],
  [ 11, 'Henry Schein Inc. v. Archer and White Sales Inc.' ],
  [ 12, 'Garza v. Idaho' ],
  [ 13,
    'Washington State Department of Licensing v. Cougar Den Inc.' ],
  [ 14, 'Frank v. Gaos' ],
  [ 15, 'Jam v. Int\'l Finance Corp.' ],
  [ 16, 'Virginia Uranium v. Warren' ],
  [ 17, 'Sturgeon v. Frost' ],
  [ 18, 'BNSF Railway Company v. Loos' ],
  [ 19, 'Bucklew v. Precythe' ],
  [ 20, 'Culbertson v. Berryhill' ],
  [ 21, 'Republic of Sudan v. Harrison' ],
  [ 22, 'Nieves v. Bartlett' ],
  [ 23, 'Apple Inc. v. Pepper' ],
  [ 24, 'Nutraceutical Corp. v. Lambert' ],
  [ 25, 'Timbs v. Indiana' ],
  [ 26, 'Dawson v. Steager' ],
  [ 27, 'Lorenzo v. Securities and Exchange Commission' ],
  [ 28,
    'Helsinn Healthcare S.A. v. Teva Pharmaceuticals USA Inc.' ],
  [ 29, 'Biestek v. Berryhill' ],
  [ 30, 'Gamble v. U.S.' ],
  [ 31, 'Merck Sharp & Dohme Corp. v. Albrecht' ],
  [ 32, 'Obduskey v. McCarthy & Holthus LLP' ],
  [ 33, 'Fourth Estate Public Benefit Corp. v. Wall-Street.com' ],
  [ 34, 'Herrera v. Wyoming' ],
  [ 35, 'Franchise Tax Board of California v. Hyatt' ],
  [ 36, 'Thacker v. Tennessee Valley Authority' ],
  [ 37, 'Rimini Street Inc. v. Oracle USA Inc.' ],
  [ 38, 'Home Depot U.S.A. Inc. v. Jackson' ],
  [ 39, 'Azar v. Allina Health Services' ],
  [ 40, 'Knick v. Township of Scott, Pennsylvania' ],
  [ 41,
    'Tennessee Wine & Spirits Retailers Association v. Thomas' ],
  [ 42, 'Return Mail Inc. v. U.S. Postal Service' ],
  [ 43, 'Mission Product Holdings Inc. v. Tempnology, LLC' ],
  [ 44, 'Manhattan Community Access Corp. v. Halleck' ],
  [ 45, 'Mont v. U.S.' ],
  [ 46, 'U.S. v. Haymond' ],
  [ 47, 'The American Legion v. American Humanist Association' ],
  [ 48,
    'Maryland-National Capital Park and Planning Commission v. American Humanist Association' ],
  [ 49, 'Virginia House of Delegates v. Bethune-Hill' ],
  [ 50, 'Smith v. Berryhill' ],
  [ 51, 'Cochise Consultancy Inc. v. U.S., ex rel. Hunt' ],
  [ 52, 'Flowers v. Mississippi' ],
  [ 53, 'The Dutra Group v. Batterton' ],
  [ 54, 'PDR Network, LLC v. Carlton & Harris Chiropractic Inc.' ],
  [ 55, 'Lamone v. Benisek' ],
  [ 56, 'Rucho v. Common Cause' ],
  [ 57, 'Kisor v. Wilkie' ],
  [ 58, 'Iancu v. Brunetti' ],
  [ 59, 'Emulex Corp. v. Varjabedian' ],
  [ 60,
    'North Carolina Department of Revenue v. The Kimberley Rice Kaestner 1992 Family Trust' ],
  [ 61, 'Parker Drilling Management Services, Ltd. v. Newton' ],
  [ 62, 'McDonough v. Smith' ],
  [ 63, 'U.S. v. Davis' ],
  [ 64, 'Fort Bend County, Texas v. Davis' ],
  [ 65, 'Food Marketing Institute v. Argus Leader Media' ],
  [ 66, 'Mitchell v. Wisconsin' ],
  [ 67, 'Department of Commerce v. New York' ],
  [ 68, 'Rehaif v. U.S.' ],
  [ 69, 'Taggart v. Lorenzen' ],
  [ 70, 'Quarles v. U.S.' ],
  [ 71, 'City of Escondido, California v. Emmons' ],
  [ 72, 'Shoop v. Hill' ],
  [ 73, 'Yovino v. Rizo' ],
  [ 74, 'Moore v. Texas' ],
  [ 75, 'Box v. Planned Parenthood of Indiana and Kentucky Inc.' ],
  [ 76, 'Gray v. Wilkie' ],
  [ 77,
    'Department of Commerce v. U.S. District Court for the Southern District of New York' ],
  [ 78, 'Carpenter v. Murphy' ] ]