[
  [ 0, 'Delaware v. Pennsylvania and Wisconsin' ],
  [ 1, 'Sackett v. Environmental Protection Agency' ],
  [ 2, 'Allen v. Milligan' ],
  [ 3, 'Arellano v. McDonough' ],
  [ 4, 'National Pork Producers Council v. Ross' ],
  [ 5, 'Reed v. Goertz' ],
  [ 6, 'Helix Energy Solutions Group v. Hewitt' ],
  [ 7, 'Andy Warhol Foundation for the Visual Arts v. Goldsmith' ],
  [ 8, 'Students for Fair Admissions v. University of North Carolina' ],
  [
    9,
    'Students for Fair Admissions Inc. v. President & Fellows of Harvard College'
  ],
  [ 10, 'Jones v. Hendrix' ],
  [ 11, 'Cruz v. Arizona' ],
  [ 12, 'Bittner v. U.S.' ],
  [ 13, 'Axon Enterprise v. Federal Trade Commission' ],
  [ 14, 'Mallory v. Norfolk Southern Railway Co.' ],
  [
    15,
    'Health and Hospital Corporation of Marion County, Indiana v. Talevski'
  ],
  [ 16, 'Haaland v. Brackeen' ],
  [ 17, 'Ciminelli v. U.S.' ],
  [ 18, 'Percoco v. U.S.' ],
  [ 19, 'U.S. v. Texas' ],
  [ 20, 'Wilkins v. U.S.' ],
  [ 21, 'MOAC Mall Holdings LLC v. Transform Holdco LLC' ],
  [ 22, '303 Creative LLC v. Elenis' ],
  [ 23, 'U.S., ex rel. Polansky v. Executive Health Resources' ],
  [ 24, 'Bartenwerfer v. Buckley' ],
  [ 25, 'Moore v. Harper' ],
  [
    26,
    'Ohio Adjutant General’s Department v. Federal Labor Relations Authority'
  ],
  [ 27, 'In re Grand Jury' ],
  [ 28, "Glacier Northwest v. Int'l Brotherhood of Teamsters" ],
  [
    29,
    'Financial Oversight and Management Board for Puerto Rico v. Centro de Periodismo Investigativo'
  ],
  [ 30, 'Turkiye Halk Bankasi A.S. v. U.S.' ],
  [ 31, 'Santos-Zacaria v. Garland' ],
  [ 32, 'Perez v. Sturgis Public Schools' ],
  [ 33, 'Gonzalez v. Google LLC' ],
  [ 34, 'Twitter v. Taamneh' ],
  [ 35, 'Dubin v. U.S.' ],
  [ 36, 'Biden v. Nebraska' ],
  [ 37, 'Department of Education v. Brown' ],
  [ 38, 'New York v. New Jersey' ],
  [ 39, 'Arizona v. Navajo Nation' ],
  [ 40, 'Coinbase v. Bielski' ],
  [ 41, "Abitron Austria GmbH v. Hetronic Int'l" ],
  [ 42, 'Jack Daniel’s Properties v. VIP Products LLC' ],
  [ 43, 'U.S. v. Hansen' ],
  [ 44, 'Amgen Inc. v. Sanofi' ],
  [ 45, 'Lora v. U.S.' ],
  [ 46, 'Smith v. U.S.' ],
  [ 47, 'Samia v. U.S.' ],
  [ 48, 'Polselli v. Internal Revenue Service' ],
  [ 49, 'Slack Technologies v. Pirani' ],
  [ 50, 'Pugin v. Garland' ],
  [ 51, 'Groff v. DeJoy' ],
  [ 52, 'U.S. ex rel. Schutte v. SuperValu Inc.' ],
  [ 53, 'Counterman v. Colorado' ],
  [
    54,
    'Lac du Flambeau Band of Lake Superior Chippewa Indians v. Coughlin'
  ],
  [ 55, 'Dupree v. Younger' ],
  [ 56, 'Yegiazaryan v. Smagin' ],
  [ 57, 'Tyler v. Hennepin County, Minnesota' ],
  [ 58, 'Calcutt v. Federal Deposit Insurance Corp.' ],
  [ 59, 'Arizona v. Mayorkas' ]
]