module.exports = {links: [[ 3, [], [], [], [] ],
[ 16,
  [],
  [],
  [ 'https://www.scotusblog.com/wp-content/uploads/2017/06/16-1275-ac-chamber-of-commerce.pdf',
    'https://www.scotusblog.com/wp-content/uploads/2017/06/16-1275-ac-tom-cotton.pdf' ],
  [] ],
[ 13, [], [], [], [] ],
[ 34, [], [], [], [] ],
[ 35,
  [],
  [],
  [ 'https://www.scotusblog.com/wp-content/uploads/2018/01/17-532-cert-tsac-indian-law-professor.pdf',
    'https://www.scotusblog.com/wp-content/uploads/2018/01/17-532-cert-tsac-crow-tribe.pdf',
    'https://www.scotusblog.com/wp-content/uploads/2018/01/17-532-cert-tsac-Anthropologists.pdf' ],
  [] ],
[ 24, [], [], [], [] ],
[ 49,
  [ 'http://www.americanbar.org/content/dam/aba/publications/supreme_court_preview/briefs-v2/12-696_pet_amcu_bcf.authcheckdam.pdf',
    'http://www.americanbar.org/content/dam/aba/publications/supreme_court_preview/briefs-v2/12-696_pet_amcu_jff.authcheckdam.pdf',
    'http://www.americanbar.org/content/dam/aba/publications/supreme_court_preview/briefs-v2/12-696_np_amcu_lcc.authcheckdam.pdf',
    'http://www.americanbar.org/content/dam/aba/publications/supreme_court_preview/briefs-v2/12-696_pet_amcu_dr-dla-etal.authcheckdam.pdf',
    'http://www.americanbar.org/content/dam/aba/publications/supreme_court_preview/briefs-v2/12-696_pet_amcu_sbcerlc.authcheckdam.pdf',
    'http://www.americanbar.org/content/dam/aba/publications/supreme_court_preview/briefs-v2/12-696_pet_amcu_slf.authcheckdam.pdf',
    'http://www.americanbar.org/content/dam/aba/publications/supreme_court_preview/briefs-v2/12-696_pet_amcu_liberty-c.authcheckdam.pdf',
    'http://www.americanbar.org/content/dam/aba/publications/supreme_court_preview/briefs-v2/12-696_pet_amcu_sosc.authcheckdam.pdf',
    'http://www.americanbar.org/content/dam/aba/publications/supreme_court_preview/briefs-v2/12-696_pet_amcu_us-sen.authcheckdam.pdf',
    'http://www.americanbar.org/content/dam/aba/publications/supreme_court_preview/briefs-v2/12-696_pet_amcu_acru.authcheckdam.pdf',
    'http://www.americanbar.org/content/dam/aba/publications/supreme_court_preview/briefs-v2/12-696_pet_amcu_aclj.authcheckdam.pdf',
    'http://www.americanbar.org/content/dam/aba/publications/supreme_court_preview/briefs-v2/12-696_pet_amcu_nl.authcheckdam.pdf',
    'http://www.americanbar.org/content/dam/aba/publications/supreme_court_preview/briefs-v2/12-696_pet_amcu_carl.authcheckdam.pdf',
    'http://www.americanbar.org/content/dam/aba/publications/supreme_court_preview/briefs-v2/12-696_pet_amcu_vca-etal.authcheckdam.pdf',
    'http://www.americanbar.org/content/dam/aba/publications/supreme_court_preview/briefs-v2/12-696_pet_amcu_rdrep.authcheckdam.pdf',
    'http://www.americanbar.org/content/dam/aba/publications/supreme_court_preview/briefs-v2/12-696_pet_amcu_moc.authcheckdam.pdf',
    'http://www.americanbar.org/content/dam/aba/publications/supreme_court_preview/briefs-v2/12-696_pet_amcu_cfcj.authcheckdam.pdf',
    'http://www.americanbar.org/content/dam/aba/publications/supreme_court_preview/briefs-v2/12-696_pet_amcu_gvb-etal.authcheckdam.pdf',
    'http://www.americanbar.org/content/dam/aba/publications/supreme_court_preview/briefs-v2/12-696_pet_amcu_rutherford.authcheckdam.pdf',
    'http://www.americanbar.org/content/dam/aba/images/public_education/12-696_resp_amcu_fml.pdf',
    'http://www.americanbar.org/content/dam/aba/images/public_education/12-696_pet_amcu_bfrl.pdf',
    'http://www.americanbar.org/content/dam/aba/publications/supreme_court_preview/briefs-v2/12-696_pet_amcu_7pg.authcheckdam.pdf',
    'http://www.americanbar.org/content/dam/aba/publications/supreme_court_preview/briefs-v2/12-696_pet_amcu_wbi.authcheckdam.pdf',
    'http://sblog.s3.amazonaws.com/wp-content/uploads/2013/08/Town_of_Greece_v._Galloway-Amicus-States.pdf',
    'http://www.americanbar.org/content/dam/aba/publications/supreme_court_preview/briefs-v2/12-696_pet_amcu_ccc_etal.authcheckdam.pdf' ],
  [ 'http://www.americanbar.org/content/dam/aba/publications/supreme_court_preview/briefs-v2/12-696_pet_amicu_lawprofessors.authcheckdam.pdf',
    'http://www.americanbar.org/content/dam/aba/publications/supreme_court_preview/briefs-v2/12-696_amici_chemerisk_Greece.authcheckdam.pdf',
    'http://www.americanbar.org/content/dam/aba/publications/supreme_court_preview/briefs-v2/12-696_pet_amcu_Baptist.authcheckdam.pdf',
    'http://www.americanbar.org/content/dam/aba/publications/supreme_court_preview/briefs-v2/12-696_GreecePolitical%20Scientists.authcheckdam.pdf',
    'http://sblog.s3.amazonaws.com/wp-content/uploads/2013/11/249571_Brief1.pdf',
    'http://www.americanbar.org/content/dam/aba/publications/supreme_court_preview/briefs-v2/12-696_resp_amcu_uuac-etal.authcheckdam.pdf',
    'http://www.americanbar.org/content/dam/aba/publications/supreme_court_preview/briefs-v2/12-696_resp_amcu_ajc-jcpa.authcheckdam.pdf',
    'http://www.americanbar.org/content/dam/aba/publications/supreme_court_preview/briefs-v2/12-696_resp_amcu_ffrf.authcheckdam.pdf',
    'http://www.americanbar.org/content/dam/aba/publications/supreme_court_preview/briefs-v2/12-696_resp_amcu_cfi-etal.authcheckdam.pdf',
    'http://www.americanbar.org/content/dam/aba/publications/supreme_court_preview/briefs-v2/12-696_resp_amcu_nccj.authcheckdam.pdf',
    'http://www.americanbar.org/content/dam/aba/publications/supreme_court_preview/briefs-v2/12-696_resp_amcu_pf-etal.authcheckdam.pdf',
    'http://www.americanbar.org/content/dam/aba/publications/supreme_court_preview/briefs-v2/12-696_resp_amcu_aclu-etal.authcheckdam.pdf' ],
  [ 'http://sblog.s3.amazonaws.com/wp-content/uploads/2013/01/Palmer-Amicus-Brief-12-696.pdf',
    'http://sblog.s3.amazonaws.com/wp-content/uploads/2013/01/12-696-Amici-Brief-GALLOWAY.pdf',
    'http://sblog.s3.amazonaws.com/wp-content/uploads/2013/01/Greece-Members-of-Congress-Amicus.pdf',
    'http://sblog.s3.amazonaws.com/wp-content/uploads/2013/01/12-696-Amici-Brief-filed-by-Liberty-Institute.pdf',
    'http://sblog.s3.amazonaws.com/wp-content/uploads/2013/01/Galloway-Amicus-Brief-of-the-States-FINAL.pdf' ],
  [ 'http://www.americanbar.org/content/dam/aba/publications/supreme_court_preview/briefs-v2/12-696_pet_amcu_usa.authcheckdam.pdf' ] ],
[ 2, [], [], [], [] ],
[ 20, [], [], [], [] ],
[ 11, [], [], [], [] ],
[ 40, [], [], [], [] ],
[ 77, [], [], [], [] ],
[ 32, [], [], [], [] ],
[ 41, [], [], [], [] ],
[ 79, [], [], [], [] ],
[ 27, [], [], [], [] ],
[ 14, [], [], [], [] ],
[ 44, [], [], [], [] ],
[ 33,
  [],
  [],
  [ 'https://www.scotusblog.com/wp-content/uploads/2017/12/17-290-cert-tsac-PhRMA-Amicus-Brief.pdf',
    'https://www.scotusblog.com/wp-content/uploads/2017/12/No.-17-290-cert-tsac-PLAC.pdf' ],
  [] ],
[ 22, [], [], [], [] ],
[ 18, [], [], [], [] ],
[ 47, [], [], [], [] ],
[ 64, [], [], [], [] ],
[ 30, [], [], [], [] ],
[ 1, [], [], [], [] ],
[ 9, [], [], [], [] ],
[ 6, [], [], [], [] ],
[ 15, [], [], [], [] ],
[ 7, [], [], [], [] ],
[ 8,
  [],
  [],
  [],
  [ 'https://www.scotusblog.com/wp-content/uploads/2018/04/16-1363-petition.pdf',
    'https://www.scotusblog.com/wp-content/uploads/2018/04/16-1363-cert-rb.pdf' ] ],
[ 68, [], [], [], [] ],
[ 10, [], [], [], [] ],
[ 12,
  [],
  [],
  [ 'https://www.scotusblog.com/wp-content/uploads/2017/10/16-1498-cert-tsac-states-of-idaho.pdf',
    'https://www.scotusblog.com/wp-content/uploads/2017/10/16-1498-cert-tsac-WOMA.pdf',
    'https://www.scotusblog.com/wp-content/uploads/2017/10/16-1498-cert-tsac-confederated-tribes.pdf' ],
  [] ],
[ 37, [], [], [], [] ],
[ 73, [], [], [], [] ],
[ 23, [], [], [], [] ],
[ 4,
  [],
  [],
  [ 'https://www.scotusblog.com/wp-content/uploads/2017/10/17-340-cert-tsac-ATA.pdf',
    'https://www.scotusblog.com/wp-content/uploads/2017/10/17-340-cert-amicus-chamber-of-commerce.pdf' ],
  [] ],
[ 66, [], [], [], [] ],
[ 21,
  [],
  [],
  [ 'https://www.scotusblog.com/wp-content/uploads/2017/04/16-1094-cert-amicus-UAE.pdf',
    'https://www.scotusblog.com/wp-content/uploads/2017/04/16-1094-cert-amicus-TheKingdomOfSaudiArabia.pdf',
    'https://www.scotusblog.com/wp-content/uploads/2017/04/16-1094-cert-amicus-InternationalLawProfessors.pdf',
    'https://www.scotusblog.com/wp-content/uploads/2017/04/16-1094-cert-amicus-GovernmentOfNationalAccordStateOfLibya.pdf' ],
  [] ],
[ 65, [], [], [], [] ],
[ 57, [], [], [], [] ],
[ 39, [], [], [], [] ],
[ 19, [], [], [], [] ],
[ 67, [], [], [], [] ],
[ 71, [], [], [], [] ],
[ 42, [], [], [], [] ],
[ 69, [], [], [], [] ],
[ 38, [], [], [], [] ],
[ 17, [], [], [], [] ],
[ 74, [], [], [], [] ],
[ 26, [], [], [], [] ],
[ 45, [], [], [], [] ],
[ 75,
  [ 'https://www.scotusblog.com/wp-content/uploads/2016/08/15-797-ACLU-amicus-pet.pdf',
    'https://www.scotusblog.com/wp-content/uploads/2016/08/15-797_amicus_pet_international_organizations_and_individuals_interested_in_medical_expertise_and_psychiatry.pdf',
    'https://www.scotusblog.com/wp-content/uploads/2016/08/15-797_amicus_pet_american_psychological_association_et_al.pdf',
    'https://www.scotusblog.com/wp-content/uploads/2016/08/15-797-ABA-amicus-pet.pdf',
    'https://www.scotusblog.com/wp-content/uploads/2016/08/15-797_amicus_pet_american_association_on_intellectual_and_developmental_disabilities.pdf',
    'https://www.scotusblog.com/wp-content/uploads/2016/08/15-797-amicus-pet-Constitution-Project.pdf' ],
  [ 'https://www.scotusblog.com/wp-content/uploads/2016/09/15-797-amicus-respondent-arizona.pdf',
    'https://www.scotusblog.com/wp-content/uploads/2016/09/15-797-amicus-respondent-CJLF.pdf' ],
  [ 'https://www.scotusblog.com/wp-content/uploads/2016/04/Moore_v_Texas_Amicus_Final.pdf',
    'https://www.scotusblog.com/wp-content/uploads/2016/04/2016.01.19-Brief-of-Amici-Curiae-NCRAT-Reprieve-US-CCR.pdf',
    'https://www.scotusblog.com/wp-content/uploads/2016/04/Intl-Medical-Organizations-et-al-Amicus-Brief.pdf',
    'https://www.scotusblog.com/wp-content/uploads/2016/04/Intl-Human-Rights-Institutes-et-al-Amicus-Brief.pdf',
    'https://www.scotusblog.com/wp-content/uploads/2016/04/Bobby-James-Moore-v-Texas-amicus.pdf' ],
  [] ],
[ 48, [], [], [], [] ],
[ 76, [], [], [], [] ],
[ 72, [], [], [], [] ],
[ 43, [], [], [], [] ],
[ 50, [], [], [], [] ],
[ 51, [], [], [], [] ],
[ 25, [], [], [], [] ],
[ 52, [], [], [], [] ],
[ 5, [], [], [], [] ],
[ 54, [], [], [], [] ],
[ 53, [], [], [], [] ],
[ 31, [], [], [], [] ],
[ 56, [], [], [], [] ],
[ 0,
  [],
  [],
  [ 'https://www.scotusblog.com/wp-content/uploads/2018/01/17-71-17-74-cert-tsac-st-tammany.pdf',
    'https://www.scotusblog.com/wp-content/uploads/2018/01/17-71-17-74-cert-tsac-Mountain-States.pdf',
    'https://www.scotusblog.com/wp-content/uploads/2018/01/17-71-17-74-cert-tsac-WLF.pdf',
    'https://www.scotusblog.com/wp-content/uploads/2018/01/17-71-17-74-cert-tsac-CCJ.pdf',
    'https://www.scotusblog.com/wp-content/uploads/2018/01/17-71-17-74-cert-tsac-Chamber-of-Commerce.pdf',
    'https://www.scotusblog.com/wp-content/uploads/2018/01/17-71-cert-tsac-Energy-and-Wildlife-Action-Coalition.pdf',
    'https://www.scotusblog.com/wp-content/uploads/2018/01/17-71-cert-tsac-AFBF.pdf',
    'https://www.scotusblog.com/wp-content/uploads/2018/01/17-71-17-74-cert-tsac-san-juan-cty.pdf',
    'https://www.scotusblog.com/wp-content/uploads/2018/01/17-71-17-74-cert-tsac-SLF.pdf',
    'https://www.scotusblog.com/wp-content/uploads/2018/01/17-71-17-74-cert-tsac-NAHB.pdf',
    'https://www.scotusblog.com/wp-content/uploads/2018/01/17-71-17-74-tsac-Cato-Institute.pdf',
    'https://www.scotusblog.com/wp-content/uploads/2018/01/17-71-17-74-cert-tsac-alabama.pdf' ],
  [] ],
[ 61, [], [], [], [] ],
[ 59, [], [], [], [] ],
[ 78, [], [], [], [] ],
[ 46, [], [], [], [] ],
[ 36, [], [], [], [] ],
[ 62, [], [], [], [] ],
[ 60, [], [], [], [] ],
[ 58, [], [], [], [] ],
[ 63, [], [], [], [] ],
[ 28, [], [], [], [] ],
[ 29, [], [], [], [] ],
[ 55, [], [], [], [] ],
[ 70, [], [], [], [] ]]}